import {
    Code,
    Rocket,
    Palette,
    Blocks,
    Boxes,
    FileCode,
    Database,
    Server,
    Globe,
    Sparkles,
    Cpu,
    GitBranch,
    Layers,
    Workflow,
    Settings,
    Cloud,
    CloudUpload,
    Terminal,
    BookOpen,
    LayoutTemplate,
    ClipboardList,
    Hammer,
    Frame,
    PenTool,
    Binary,
    TestTube,
    MessageSquare,
} from 'lucide-react';

export interface Skill {
    name: string;
    icon: React.ElementType;
}

export const technicalSkills: Skill[] = [
    { name: 'React', icon: Blocks },
    { name: 'TypeORM', icon: Layers },
    { name: 'Next.js', icon: Rocket },
    { name: 'TypeScript', icon: FileCode },
    { name: 'JavaScript', icon: Code },
    { name: 'HTML5', icon: Globe },
    { name: 'Node.js', icon: Server },
    { name: 'CSS3', icon: Palette },
    { name: 'Bootstrap', icon: LayoutTemplate },
    { name: 'jQuery', icon: Boxes },
    { name: 'Figma', icon: PenTool },
    { name: 'Shadcn/UI', icon: Frame },
    { name: 'PostgreSQL', icon: Database },
    { name: 'Framer Motion', icon: Sparkles },
    { name: 'Express', icon: Server },
    { name: 'Java', icon: Cpu },
    { name: 'Tailwind CSS', icon: Palette },
    { name: '.NET', icon: Settings },
    { name: 'MySQL', icon: Database },
    { name: 'Prisma', icon: Layers },
    { name: 'SQL', icon: Binary },
    { name: 'Jest', icon: TestTube },
    { name: 'Git & GitHub', icon: GitBranch },
    { name: 'Scrum', icon: Workflow },
    { name: 'Kanban', icon: ClipboardList },
    { name: 'C#', icon: Cpu },
    { name: 'XP', icon: Hammer },
    { name: 'Vercel', icon: CloudUpload },
    { name: 'Render', icon: Cloud },
    { name: 'Supabase', icon: Database },
    { name: 'Postman', icon: Terminal },
    { name: 'Trello', icon: ClipboardList },
    { name: 'Slack', icon: MessageSquare },
    { name: 'Notion', icon: BookOpen },
];
