import {
    Code,
    Rocket,
    Palette,
    Blocks,
    Boxes,
    FileCode,
    Database,
    Server,
    Globe,
    Sparkles,
    Cpu,
    GitBranch,
    Layers,
    Workflow,
    Settings,
    Cloud,
    CloudUpload,
    Terminal,
    BookOpen,
    LayoutTemplate,
    ClipboardList,
    Hammer,
    Frame,
    PenTool,
    Binary,
    TestTube,
    MessageSquare,
} from 'lucide-react';

export interface Skill {
    name: string;
    icon: React.ElementType;
    description: string;
}

export const technicalSkills: Skill[] = [
    { name: 'React', icon: Blocks, description: 'Librería para construir interfaces dinámicas.' },
    { name: 'Next.js', icon: Rocket, description: 'Framework para apps rápidas con React y SSR.' },
    { name: 'TypeScript', icon: FileCode, description: 'JavaScript tipado para mayor robustez.' },
    { name: 'JavaScript', icon: Code, description: 'Lenguaje base para desarrollo web moderno.' },
    { name: 'HTML5', icon: Globe, description: 'Estructura semántica para la web.' },
    { name: 'CSS3', icon: Palette, description: 'Estilos y diseño responsivo.' },
    { name: 'Tailwind CSS', icon: Palette, description: 'Framework de utilidades para estilos rápidos.' },
    { name: 'Bootstrap', icon: LayoutTemplate, description: 'Componentes listos para maquetado ágil.' },
    { name: 'jQuery', icon: Boxes, description: 'Manipulación del DOM y utilidades JS.' },
    { name: 'Figma', icon: PenTool, description: 'Diseño UI/UX y prototipado colaborativo.' },
    { name: 'Shadcn/UI', icon: Frame, description: 'Componentes accesibles y personalizables.' },
    { name: 'Framer Motion', icon: Sparkles, description: 'Animaciones fluidas para React.' },
    { name: 'Node.js', icon: Server, description: 'Entorno para ejecutar JavaScript del lado del servidor.' },
    { name: 'Express', icon: Server, description: 'Framework para crear APIs ligeras en Node.' },
    { name: 'Java', icon: Cpu, description: 'Lenguaje orientado a objetos robusto.' },
    { name: 'C#', icon: Cpu, description: 'Lenguaje moderno para apps .NET.' },
    { name: '.NET', icon: Settings, description: 'Framework para desarrollo multiplataforma.' },
    { name: 'PostgreSQL', icon: Database, description: 'Base de datos SQL potente y flexible.' },
    { name: 'MySQL', icon: Database, description: 'Base de datos SQL ampliamente utilizada.' },
    { name: 'Prisma', icon: Layers, description: 'ORM moderno para bases de datos SQL.' },
    { name: 'TypeORM', icon: Layers, description: 'ORM para Node con soporte a múltiples DB.' },
    { name: 'SQL', icon: Binary, description: 'Lenguaje para consultas y gestión de datos.' },
    { name: 'Jest', icon: TestTube, description: 'Testing de JavaScript y TypeScript.' },
    { name: 'Git & GitHub', icon: GitBranch, description: 'Control de versiones y repositorios.' },
    { name: 'Scrum', icon: Workflow, description: 'Metodología ágil para trabajo en equipo.' },
    { name: 'Kanban', icon: ClipboardList, description: 'Gestión visual del flujo de trabajo.' },
    { name: 'XP', icon: Hammer, description: 'Prácticas ágiles enfocadas en calidad.' },
    { name: 'Vercel', icon: CloudUpload, description: 'Hosting optimizado para apps Next.js.' },
    { name: 'Render', icon: Cloud, description: 'Plataforma para desplegar webs y APIs.' },
    { name: 'Supabase', icon: Database, description: 'Backend completo con base de datos Postgres.' },
    { name: 'Postman', icon: Terminal, description: 'Testing y documentación de APIs.' },
    { name: 'Trello', icon: ClipboardList, description: 'Gestión visual de tareas y proyectos.' },
    { name: 'Slack', icon: MessageSquare, description: 'Comunicación y colaboración en equipos.' },
    { name: 'Notion', icon: BookOpen, description: 'Organización, documentación y notas.' },
    { name: 'React', icon: Blocks, description: 'Librería para construir interfaces dinámicas.' },
    { name: 'Next.js', icon: Rocket, description: 'Framework para apps rápidas con React y SSR.' },
    { name: 'TypeScript', icon: FileCode, description: 'JavaScript tipado para mayor robustez.' },
    { name: 'JavaScript', icon: Code, description: 'Lenguaje base para desarrollo web moderno.' },
    { name: 'HTML5', icon: Globe, description: 'Estructura semántica para la web.' },
    { name: 'CSS3', icon: Palette, description: 'Estilos y diseño responsivo.' },
    { name: 'Tailwind CSS', icon: Palette, description: 'Framework de utilidades para estilos rápidos.' },
    { name: 'Bootstrap', icon: LayoutTemplate, description: 'Componentes listos para maquetado ágil.' },
    { name: 'jQuery', icon: Boxes, description: 'Manipulación del DOM y utilidades JS.' },
    { name: 'Figma', icon: PenTool, description: 'Diseño UI/UX y prototipado colaborativo.' },
    { name: 'Shadcn/UI', icon: Frame, description: 'Componentes accesibles y personalizables.' },
    { name: 'Framer Motion', icon: Sparkles, description: 'Animaciones fluidas para React.' },
    { name: 'Node.js', icon: Server, description: 'Entorno para ejecutar JavaScript del lado del servidor.' },
    { name: 'Express', icon: Server, description: 'Framework para crear APIs ligeras en Node.' },
    { name: 'Java', icon: Cpu, description: 'Lenguaje orientado a objetos robusto.' },
    { name: 'C#', icon: Cpu, description: 'Lenguaje moderno para apps .NET.' },
    { name: '.NET', icon: Settings, description: 'Framework para desarrollo multiplataforma.' },
    { name: 'PostgreSQL', icon: Database, description: 'Base de datos SQL potente y flexible.' },
    { name: 'MySQL', icon: Database, description: 'Base de datos SQL ampliamente utilizada.' },
    { name: 'Prisma', icon: Layers, description: 'ORM moderno para bases de datos SQL.' },
    { name: 'TypeORM', icon: Layers, description: 'ORM para Node con soporte a múltiples DB.' },
    { name: 'SQL', icon: Binary, description: 'Lenguaje para consultas y gestión de datos.' },
    { name: 'Jest', icon: TestTube, description: 'Testing de JavaScript y TypeScript.' },
    { name: 'Git & GitHub', icon: GitBranch, description: 'Control de versiones y repositorios.' },
    { name: 'Scrum', icon: Workflow, description: 'Metodología ágil para trabajo en equipo.' },
    { name: 'Kanban', icon: ClipboardList, description: 'Gestión visual del flujo de trabajo.' },
    { name: 'XP', icon: Hammer, description: 'Prácticas ágiles enfocadas en calidad.' },
    { name: 'Vercel', icon: CloudUpload, description: 'Hosting optimizado para apps Next.js.' },
    { name: 'Render', icon: Cloud, description: 'Plataforma para desplegar webs y APIs.' },
    { name: 'Supabase', icon: Database, description: 'Backend completo con base de datos Postgres.' },
    { name: 'Postman', icon: Terminal, description: 'Testing y documentación de APIs.' },
    { name: 'Trello', icon: ClipboardList, description: 'Gestión visual de tareas y proyectos.' },
    { name: 'Slack', icon: MessageSquare, description: 'Comunicación y colaboración en equipos.' },
    { name: 'Notion', icon: BookOpen, description: 'Organización, documentación y notas.' },
    { name: 'React', icon: Blocks, description: 'Librería para construir interfaces dinámicas.' },
    { name: 'Next.js', icon: Rocket, description: 'Framework para apps rápidas con React y SSR.' },
    { name: 'TypeScript', icon: FileCode, description: 'JavaScript tipado para mayor robustez.' },
    { name: 'JavaScript', icon: Code, description: 'Lenguaje base para desarrollo web moderno.' },
    { name: 'HTML5', icon: Globe, description: 'Estructura semántica para la web.' },
    { name: 'CSS3', icon: Palette, description: 'Estilos y diseño responsivo.' },
    { name: 'Tailwind CSS', icon: Palette, description: 'Framework de utilidades para estilos rápidos.' },
    { name: 'Bootstrap', icon: LayoutTemplate, description: 'Componentes listos para maquetado ágil.' },
    { name: 'jQuery', icon: Boxes, description: 'Manipulación del DOM y utilidades JS.' },
    { name: 'Figma', icon: PenTool, description: 'Diseño UI/UX y prototipado colaborativo.' },
    { name: 'Shadcn/UI', icon: Frame, description: 'Componentes accesibles y personalizables.' },
    { name: 'Framer Motion', icon: Sparkles, description: 'Animaciones fluidas para React.' },
    { name: 'Node.js', icon: Server, description: 'Entorno para ejecutar JavaScript del lado del servidor.' },
    { name: 'Express', icon: Server, description: 'Framework para crear APIs ligeras en Node.' },
    { name: 'Java', icon: Cpu, description: 'Lenguaje orientado a objetos robusto.' },
    { name: 'C#', icon: Cpu, description: 'Lenguaje moderno para apps .NET.' },
    { name: '.NET', icon: Settings, description: 'Framework para desarrollo multiplataforma.' },
    { name: 'PostgreSQL', icon: Database, description: 'Base de datos SQL potente y flexible.' },
    { name: 'MySQL', icon: Database, description: 'Base de datos SQL ampliamente utilizada.' },
    { name: 'Prisma', icon: Layers, description: 'ORM moderno para bases de datos SQL.' },
    { name: 'TypeORM', icon: Layers, description: 'ORM para Node con soporte a múltiples DB.' },
    { name: 'SQL', icon: Binary, description: 'Lenguaje para consultas y gestión de datos.' },
    { name: 'Jest', icon: TestTube, description: 'Testing de JavaScript y TypeScript.' },
    { name: 'Git & GitHub', icon: GitBranch, description: 'Control de versiones y repositorios.' },
    { name: 'Scrum', icon: Workflow, description: 'Metodología ágil para trabajo en equipo.' },
    { name: 'Kanban', icon: ClipboardList, description: 'Gestión visual del flujo de trabajo.' },
    { name: 'XP', icon: Hammer, description: 'Prácticas ágiles enfocadas en calidad.' },
    { name: 'Vercel', icon: CloudUpload, description: 'Hosting optimizado para apps Next.js.' },
    { name: 'Render', icon: Cloud, description: 'Plataforma para desplegar webs y APIs.' },
    { name: 'Supabase', icon: Database, description: 'Backend completo con base de datos Postgres.' },
    { name: 'Postman', icon: Terminal, description: 'Testing y documentación de APIs.' },
    { name: 'Trello', icon: ClipboardList, description: 'Gestión visual de tareas y proyectos.' },
    { name: 'Slack', icon: MessageSquare, description: 'Comunicación y colaboración en equipos.' },
    { name: 'Notion', icon: BookOpen, description: 'Organización, documentación y notas.' },
];
